languageCode = "en"
languageName = "English"
weight = 1
title = "The blogs of GhostVaibhav"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "vs.png"
  # secondaryLogo = "vs.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Vaibhav Sharma"
  image = "vs.png"
  headline = "Aspiring software developer getting his hands dirty in all technologies"
  bio = "Aspiring software developer getting his hands dirty in all technologies"
   links = [
     { email = "mailto:sharmavaibhav110028@gmail.com" },
     { link = "https://ghostvaibhav.codes/" },
     { dev = "https://dev.to/ghostvaibhav" },
#     { discord = "https://discord.gg/invitecode" },
#     { facebook = "https://facebook.com/username" },
     { github = "https://github.com/GhostVaibhav" },
#     { instagram = "https://instagram.com/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/ghost-vaibhav" },
     { medium = "https://medium.com/@ghostvaibhav" },
#     { reddit = "https://reddit.com/user/username" },
#     { soundcloud = "https://soundcloud.com/username" },
     { stack-overflow = "https://stackoverflow.com/users/12634085/ghostvaibhav" },
     { steam = "https://steamcommunity.com/id/ghostvaibhav" },
#     { twitch = "https://twitch.tv/username" },
     { x-twitter = "https://twitter.com/Ghost_Vaibhav" },
   ]
